### ISSUE TITLE
pyqstem.interface error

### ISSUE THREAD

**Issue by cphatak** [jacobjma/PyQSTEM#7]
Hi,

I was trying to install PyQSTEM on Mac OS X 10.12.6. As per the instructions, everything was installed correctly with few warnings but when trying to import pyqstem, I get the following error - 

Python 3.6.0 |Anaconda custom (x86_64)| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyqstem import PyQSTEM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cphatak/Applications/PyQSTEM/pyqstem/__init__.py", line 2, in <module>
    from pyqstem.qstem_interface import PyQSTEM
ModuleNotFoundError: No module named 'pyqstem.qstem_interface'
>>>

Any help appreciated. Thanks,

cheers,
-cd

**Comment by ImogenN** [comment]
Hi,

I'm having the same issue using windows. Appreciate any advice.

**Comment by GeekMe93** [comment]
Hi, same here...on MacOX

**Comment by daknez** [comment]
Same here, tried with python 3.7.1 on Windows 10 with anaconda and also with Ubuntu bash under Windows with python 3.6.7 (no anaconda). Compiling succeded for both but invoking pyqstem in python with "from pyqstem import PyQSTEM" leads to an error (ModuleNotFoundError: No module named 'pyqstem').
Any idea?
